### ISSUE TITLE
When SDK raises an InvalidRequest exception, the reason is not always displayed

### ISSUE THREAD

**Issue by samlesu** [SubstraFoundation/substra#35]
At least when the request is failing due to a validation error from the backend, the reason is not displayed:

```
    raise exceptions.InvalidRequest.from_request_exception(e)
substra.sdk.exceptions.InvalidRequest: 400 Client Error: Bad Request for url: http://substra-backend.node-1.com/traintuple/
```

The reason causing the failure was in the above example was:
```
{"compute_plan_id":["Ensure this field has at least 64 characters."]}
```

**Comment by maeldebon** [comment]
That's because the format returned by the backend is not always the same. 
For example, the same error (InvalidRequest) returns me this error when I try to add a traintuple which doesn't contains 64-characters keys:
```{"train_data_sample_keys": {"0": ["Ensure this field has at least 64 characters."], "1": ["Ensure this field has at least 64 characters."]}}```

In the exception itself, we are trying to get the `message` attribute, which is not always specified in the response we get.

**Comment by jmorel** [comment]
I had trouble understanding the issue until I realized this is an issue with the SDK and not the CLI. The CLI displays the full errors, although in a weird format (see #147) but the SDK doesn't display anything at all.

I tried running a script that would raise an error and here is the full output:
```sh
➜ python test.py
Requests error status 400: {"data_manager_key":["This field may not be null."],"compute_plan_id":["Ensure this field has at least 64 characters."],"train_data_sample_keys":["Ensure this field has at least 1 elements."]}
Traceback (most recent call last):
  File "/Users/jeremy/substra/substra/substra/sdk/rest_client.py", line 121, in __request
    r.raise_for_status()
  File "/Users/jeremy/.virtualenvs/substra/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://substra-backend.node-1.com/traintuple/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 15, in <module>
    c.add_traintuple(traintuple)
  File "/Users/jeremy/substra/substra/substra/sdk/client.py", line 40, in wrapper
    return f(*args, **kwargs)
  File "/Users/jeremy/substra/substra/substra/sdk/client.py", line 447, in add_traintuple
    res = self._add(assets.TRAINTUPLE, data, exist_ok=exist_ok)
  File "/Users/jeremy/substra/substra/substra/sdk/client.py", line 185, in _add
    **requests_kwargs)
  File "/Users/jeremy/substra/substra/substra/sdk/rest_client.py", line 256, in add
    return self._add(name, exist_ok=exist_ok, **request_kwargs)
  File "/Users/jeremy/substra/substra/substra/sdk/rest_client.py", line 232, in _add
    return self.request('post', name, **request_kwargs)
  File "/Users/jeremy/substra/substra/substra/sdk/utils.py", line 170, in wrapper
    return f(*args, **kwargs)
  File "/Users/jeremy/substra/substra/substra/sdk/rest_client.py", line 187, in request
    **request_kwargs,
  File "/Users/jeremy/substra/substra/substra/sdk/rest_client.py", line 165, in _request
    return self.__request(request_name, url, **request_kwargs)
  File "/Users/jeremy/substra/substra/substra/sdk/rest_client.py", line 133, in __request
    raise exceptions.InvalidRequest.from_request_exception(e)
substra.sdk.exceptions.InvalidRequest: 400 Client Error: Bad Request for url: http://substra-backend.node-1.com/traintuple/
```

The very first line is only displayed thanks to the logging library, it's not part of the traceback (see rest_client.py, L130). 

So the real goal here is to have the traceback display the error details.
