### ISSUE TITLE
KeyError with full traceback

### ISSUE THREAD

**Issue by maeldebon** [SubstraFoundation/substra#50]
When I tried to add a traintuple without the "keys" field in the --data-samples-path field, I got a full traceback instead of only an error message:

```
Traceback (most recent call last):
  File "/Users/mael/.venv/substra/bin/substra", line 11, in <module>
    load_entry_point('substra', 'console_scripts', 'substra')()
  File "/Users/mael/.venv/substra/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mael/.venv/substra/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/mael/.venv/substra/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mael/.venv/substra/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mael/.venv/substra/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mael/.venv/substra/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/mael/.venv/substra/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mael/substra/substra/substra/cli/interface.py", line 172, in wrapper
    return fn(*args, **kwargs)
  File "/Users/mael/substra/substra/substra/cli/interface.py", line 611, in add_traintuple
    data['train_data_sample_keys'] = data_samples['keys']
KeyError: 'keys'
```

**Comment by jmorel** [comment]
Fixed by #53
