### ISSUE TITLE
Local install using skaffold on MacOS

### ISSUE THREAD

**Issue by celinejacques** [SubstraFoundation/substra#73]
Following this [guide](https://github.com/SubstraFoundation/substra/blob/master/docs/local_install_skaffold.md#2-install-docker-and-kubernetes) and using minikube as suggested [here](https://github.com/SubstraFoundation/substra/issues/72#issuecomment-567929967), I have issues to run `skaffold dev` on hlf-k8s and backend. For frontend, I got the expected lines in the terminal. 

For hlf-k8s, orderer, org 1 and org 2 are deployed and then I got these warnings:
```
WARN[0051] error adding label to runtime object: patching resource org-1/network-org-1-peer-1-hlf-k8s-hook-desinstall-chaincode: jobs.batch "network-org-1-peer-1-hlf-k8s-hook-desinstall-chaincode" not found 
WARN[0057] error adding label to runtime object: patching resource org-2/network-org-2-peer-1-hlf-k8s-hook-cleanup: jobs.batch "network-org-2-peer-1-hlf-k8s-hook-cleanup" not found 
WARN[0058] error adding label to runtime object: patching resource org-2/network-org-2-peer-1-hlf-k8s-hook-desinstall-chaincode: jobs.batch "network-org-2-peer-1-hlf-k8s-hook-desinstall-chaincode" not found 
Watching for changes...
```
followed by several lines [DEBUG] and [INFO] finishing by:
```
[network-org-2-peer-1-hlf-k8s-bootstrap-peer-4qp64 fabric-tools] tar: Removing leading `/' from member names
[network-org-2-peer-1-hlf-k8s-bootstrap-peer-4qp64 fabric-tools] secret/hlf-idcert created
[network-org-2-peer-1-hlf-k8s-bootstrap-peer-4qp64 fabric-tools] secret/hlf-idkey created
[network-org-2-peer-1-hlf-k8s-bootstrap-peer-4qp64 fabric-tools] secret/hlf-cacert created
[network-org-2-peer-1-hlf-k8s-bootstrap-peer-4qp64 fabric-tools] secret/hlf-tls created
[network-org-2-peer-1-hlf-k8s-bootstrap-peer-4qp64 fabric-tools] secret/hlf-client-tls created
[network-org-2-peer-1-hlf-k8s-bootstrap-peer-4qp64 fabric-tools] secret/hlf-tlsrootcert created
[network-org-2-peer-1-hlf-k8s-bootstrap-peer-4qp64 fabric-tools] secret/hlf-client-tlsrootcert created
[network-org-2-peer-1-hlf-k8s-bootstrap-peer-4qp64 fabric-tools] secret/hlf-admincert created
[network-org-2-peer-1-hlf-k8s-bootstrap-peer-4qp64 fabric-tools] secret/hlf-adminkey created
```

and after stoping the process with `ctrl+c`:
```
Cleaning up...
Error: jobs.batch "network-orderer-hlf-k8s-hook-cleanup" already exists
Error: jobs.batch "network-org-1-peer-1-hlf-k8s-hook-cleanup" already exists
release "network-org-2-peer-1" deleted
```

For the backend, I got these kind of lines over and over:
```
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend] INFO - 2020-01-03 15:41:52,296 - events.apps - Retry to connect the event application to the ledger
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend] ERROR - 2020-01-03 15:41:53,307 - events.apps - <_MultiThreadedRendezvous of RPC that terminated with:
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend] 	status = StatusCode.UNAVAILABLE
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend] 	details = "failed to connect to all addresses"
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend] 	debug_error_string = "{"created":"@1578066113.307234644","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1578066113.307230733","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend] >
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend] Traceback (most recent call last):
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]   File "/usr/src/app/events/apps.py", line 150, in ready
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]     with get_hfc() as (loop, client):
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]   File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]     return next(self.gen)
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]   File "/usr/src/app/substrapp/ledger_utils.py", line 122, in get_hfc
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]     loop, client = LEDGER['hfc']()
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]   File "/usr/src/app/backend/settings/deps/ledger.py", line 62, in get_hfc_client
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]     decode=True
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]     return future.result()
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]   File "/usr/local/lib/python3.6/site-packages/hfc/fabric/client.py", line 1844, in query_channels
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]     res = await asyncio.gather(*responses)
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]   File "/usr/local/lib/python3.6/site-packages/aiogrpc/channel.py", line 40, in __call__
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend]     return await fut
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend] 	status = StatusCode.UNAVAILABLE
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend] 	details = "failed to connect to all addresses"
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend] 	debug_error_string = "{"created":"@1578066113.307234644","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1578066113.307230733","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
[backend-org-1-substra-backend-server-cdc97b8db-d2l79 substra-backend] >
```

I tried with minikube v1.5.1 and v1.6.0 and helm v2.16.1.

**Comment by ClementGautier** [comment]
Hello and thanks for opening the issue.

Your issue looks like you had leftover Secrets from a previous installation. I suggest you cleanup your environment using `kubectl delete ns orderer org-1 org2` (That should get rid of everything left if any). And start `skaffold dev` again.

The warnings coming from Skaffold and from some of the first jobs are expected as they are trying to reach services that are not running yet (it takes a few minutes for everything to start).

If you still have issues, could you show us the status of the various jobs and pod running and ideally a pastebin (or similar) link to the full logs.

**Comment by celinejacques** [comment]
Hello,

thank you for your help ! I reset everything and finally managed to get expected lines for backend and frontend but I still have problems with hlf-k8s. 

Now it seems stuck after these lines:

```
[network-org-1-peer-1-hlf-k8s-add-org-mychannel-myorg2-g6bz7 fabric-tools] 2020-01-07 14:38:23.763 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
[network-org-1-peer-1-hlf-k8s-add-org-mychannel-myorg2-g6bz7 fabric-tools] 2020-01-07 14:38:23.770 UTC [cli.common] readBlock -> INFO 002 Received block: 3
[network-org-1-peer-1-hlf-k8s-add-org-mychannel-myorg2-g6bz7 fabric-tools] 2020-01-07 14:38:23.772 UTC [cli.common] readBlock -> INFO 003 Received block: 1
[network-org-1-peer-1-hlf-k8s-add-org-mychannel-myorg2-g6bz7 fabric-tools] 2020-01-07 14:38:23.772 UTC [channelCmd] fetch -> INFO 004 Retrieving last config block: 1
[network-org-1-peer-1-hlf-k8s-add-org-mychannel-myorg2-g6bz7 fabric-tools] 2020-01-07 14:38:24.022 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
[network-org-1-peer-1-hlf-k8s-add-org-mychannel-myorg2-g6bz7 fabric-tools] go package net: GODEBUG setting forcing use of Go's resolver
[network-org-1-peer-1-hlf-k8s-add-org-mychannel-myorg2-g6bz7 fabric-tools] 2020-01-07 14:38:24.099 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
[network-org-1-peer-1-hlf-k8s-add-org-mychannel-myorg2-g6bz7 fabric-tools] 2020-01-07 14:38:24.115 UTC [channelCmd] update -> INFO 002 Successfully submitted channel update
[network-org-2-peer-1-hlf-k8s-channel-join-0-lgtw7 fabric-tools] 2020-01-07 14:38:25.592 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
[network-org-2-peer-1-hlf-k8s-channel-join-0-lgtw7 fabric-tools] 2020-01-07 14:38:25.598 UTC [cli.common] readBlock -> INFO 002 Received block: 0
[network-org-2-peer-1-hlf-k8s-channel-join-0-lgtw7 fabric-tools] 2020-01-07 14:38:25.652 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
[network-org-2-peer-1-hlf-k8s-channel-join-0-lgtw7 fabric-tools] 2020-01-07 14:38:25.683 UTC [channelCmd] executeJoin -> INFO 002 Successfully submitted proposal to join channel
```

Do you have any idea why it doesn't go any further? 
Thanks

**Comment by samlesu** [comment]
Hello @celinejacques, thanks for opening this issue.
That's the expected behaviour. It looks like that the hyperledger network has been started successfully.

**Comment by celinejacques** [comment]
Great then ! 
I was expecting the line given in the readme:
```
[network-org-2-peer-1-hlf-k8s-chaincode-install-0-4bdd4 fabric-tools] 2019-11-14 09:14:52.070 UTC [chaincodeCmd] install -> INFO 003 Installed remotely response:<status:200 payload:"OK" >
```
Perfect if there is the expected behaviour, I can move forward!

Thanks for your help

**Comment by ClementGautier** [comment]
It's not deterministic, some jobs run in parallel so you can't really know from the order of the logs. If all the Jobs have run successfully then yes you are good to go ;)
