### ISSUE TITLE
Error when adding train algo in titanic

### ISSUE THREAD

**Issue by chrisalexandrepena** [SubstraFoundation/substra#98]
I'm trying to run the **add_train_algo_random_forest.py** in the Titanic example on my **ubuntu server 18.04.3 LTS** environment and get the following error:

```
Adding algo...
Requests error status 409: {"message":[{"pkhash":["algo with this pkhash already exists."]}],"pkhash":"45df2bbabc90ab1ea2581609e77a2f6d07c1d9d27d734a24357b84545504ec2a"}
algo already exists: key='45df2bbabc90ab1ea2581609e77a2f6d07c1d9d27d734a24357b84545504ec2a'
Registering traintuple...
Requests error status 400: {"message":"url http://substra-backend.node-1.com/data_manager/470077b542617692152f9da3b9a24202c76032baf9d0dfd05e4ee412c0eb2ef5/opener/: hash doesn't match 470077b542617692152f9da3b9a24202c76032baf9d0dfd05e4ee412c0eb2ef5 vs 3163d83bbafed39314abe0d22419087b1ca5be2fc243c5b6b99e0ce5a344e9f0"}
Traceback (most recent call last):
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/rest_client.py", line 107, in _request
    r.raise_for_status()
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://substra-backend.node-2.com:80/data_manager/470077b542617692152f9da3b9a24202c76032baf9d0dfd05e4ee412c0eb2ef5/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/add_train_algo_random_forest.py", line 79, in <module>
    data_keys = client.get_dataset(data_manager_key)['trainDataSampleKeys']
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/client.py", line 572, in get_dataset
    return self.client.get(assets.DATASET, dataset_key)
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/rest_client.py", line 172, in get
    path=f"{key}",
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/rest_client.py", line 155, in request
    **request_kwargs,
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/rest_client.py", line 119, in _request
    raise exceptions.InvalidRequest.from_request_exception(e)
substra.sdk.exceptions.InvalidRequest: 400 Client Error: Bad Request for url: http://substra-backend.node-2.com:80/data_manager/470077b542617692152f9da3b9a24202c76032baf9d0dfd05e4ee412c0eb2ef5/: url http://substra-backend.node-1.com/data_manager/470077b542617692152f9da3b9a24202c76032baf9d0dfd05e4ee412c0eb2ef5/opener/: hash doesn't match 470077b542617692152f9da3b9a24202c76032baf9d0dfd05e4ee412c0eb2ef5 vs 3163d83bbafed39314abe0d22419087b1ca5be2fc243c5b6b99e0ce5a344e9f0
```

I'm running it on the **multinodes-examples** branch of the substra repository.

**Comment by jmorel** [comment]
This issue is related to #102 and is linked to a deployment setup issue. Closing to avoid having multiple discussions about the same underlying issue.
