### ISSUE TITLE
Error when adding train algo in titanic (2)

### ISSUE THREAD

**Issue by chrisalexandrepena** [SubstraFoundation/substra#99]
I switched to the **master** branch, installed the **keyrings.alt** dependency, and am still running in a **Ubuntu server LTS 18.04.2** environment. 
Now when I run the **add_dataset_objective.py** script I do generate a **assets_keys.json** file in my titanic base folder.
But when I try to run the **add_train_algo_random_forest.py** script I get the following error:

```
Adding algo...
Requests error status 409: {"message":[{"pkhash":["algo with this pkhash already exists."]}],"pkhash":"5d5fca19c9d72195359f6b57c6f43846e5c0a41d20f3bd1f0444cc9312e6c1a2"}
algo already exists: key='5d5fca19c9d72195359f6b57c6f43846e5c0a41d20f3bd1f0444cc9312e6c1a2'
Registering traintuple...
Requests error status 400: {"objective_key":["This field may not be null."]}
Traceback (most recent call last):
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/rest_client.py", line 107, in _request
    r.raise_for_status()
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://substra-backend.node-1.com/traintuple/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/add_train_algo_random_forest.py", line 80, in <module>
    }, exist_ok=True)
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/client.py", line 420, in add_traintuple
    res = self._add(assets.TRAINTUPLE, data, timeout=timeout, exist_ok=exist_ok)
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/client.py", line 154, in _add
    **requests_kwargs)
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/rest_client.py", line 207, in add
    **request_kwargs,
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/rest_client.py", line 155, in request
    **request_kwargs,
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/rest_client.py", line 119, in _request
    raise exceptions.InvalidRequest.from_request_exception(e)
substra.sdk.exceptions.InvalidRequest: 400 Client Error: Bad Request for url: http://substra-backend.node-1.com/traintuple/
```

I checked the content of the assets_keys.json file and the **objective_key** is specified, but for some reason it isn't passed on:

```
{
  "dataset_key": "c1d9b42d9538f825109c38c4f599d47391347d198a0770331ba790b7ebcfaa40",
  "objective_key": "1158d2f5c0cf9f80155704ca0faa28823b145b42ebdba2ca38bd726a1377e1cb",
  "train_data_sample_keys": [
    "b091986a07225b0d95e85b736a2856a717a8a0b98698b377e6048e4f861cc26d",
    "b61e5914eacf180d5db29af27e055ec2953fff2aa99347dbec4c49d34bff2270",
    "76bd8acd270d93b39d0a04fe15d8803b6041c0ca0c801fb1d96a60e572520455",
    "1c5e6be2d9341fef6288416b0edecdd0493ed13ed3ecb7361da75fc508bff019",
    "3350ec9bb4652daa74df08bc4868fe600f460f39773bce1597bfe1847b2dd0a2",
    "980a9f3da9defd7edd6fff4b728cd23762aac94931f6eb65432dc26cd9fd8997",
    "c20832fa897b6501f67ba9d93b4f77c50bf0126bdede54895058f287b13ca120",
    "df30631d848af93a7f18faef024556b0bf39b6c6a263532f7e5823035c2dc116",
    "d9f00baa90f70f8a2778970c93df49b1b6313f16ce609591b431685db584a523",
    "9542260897d66ba3d4b1479b6311ee13e7514d1091701c75186d276b54386aa9"
  ],
  "test_data_sample_keys": [
    "bb28f131a7caa5ef1b9d61f99160b7a06069ad5ce2765bdd213f2b32af2f5f81",
    "5483ea647daa49c6c6da9e2ed4a5ce6f9f7d4c029bdade549a6c8e8148c44555"
  ]
}
```

**Comment by jmorel** [comment]
The issue was due to an older version of the backend, closing.
